### ISSUE TITLE
improve runtime by big-M notation

### ISSUE THREAD

**Issue by Lorax66** [Die-KoMa/ak-plan-optimierung#4]
I assume, that the runtime of the optimizer can be improved by tightening the bound in the big-M constraint for the room size.
Replacing `num_people` by the number of people who selected the corresponding AK for each AK individually should diminish the polytope of the LP relaxation. The value is a priori known and thus can be treated as constant.

_Originally posted by @Mathemalsky in https://github.com/Die-KoMa/ak-plan-optimierung/issues/1#issuecomment-1557927043_

**Comment by felixblanke** [comment]
Duplicate of #3.
